# change to config.yaml, and fill the missing attributes accordingly
{
  "easter_eggs":{
    "SECRET1":"EGG",
    "SECRET2":"EGG2"
  },
  "quotes":[
    [
      "QUOTE1",
      "QUOTEE1",
      "SOURCE1",
      "URL1"
    ],
    [
      "QUOTE2",
      "QUOTEE2",
      "SOURCE2",
      "URL2"
    ]
  ],
  "videos":[
    "YOUTUBE_ID1",
    "YOUTUBE_ID2"
  ],
  "mongo":"mongodb+srv://MONGOHOST:MONGOPORT/DB",
  "api_key":"APIKEY",
  "redis":"redis://REDISHOST:REDISPORT",
  "limit":500, #number of requests allowed in <period>
  "period":400, # period (seconds)
  "port":"PORTNUM",
  "reload":false,
  "model_zip_id": "gdrive_file_id"
}